## Travis CI Integration

language: c

install:
  - sudo add-apt-repository ppa:ermshiperete/monodevelop
  - /n
  - sudo apt-get update
  - sudo apt-get install monodevelop-current


script:
  - xbuild TestProject2.sln
  - nunit-console TestProject2/bin/Debug/TestProject2.dll
  
