## Travis CI Integration

language: objective-c

install:
  - add-apt-repository ppa:keks9n/monodevelop-latest
  - sudo apt-get update && sudo apt-get install monodevelop-current

script:
  - xbuild TestProject2.sln
  - nunit-console TestProject2/bin/Debug/TestProject2.dll
  
