## Travis CI Integration

language: c

install:
  - deb http://www.backports.org/debian sarge-backports main contrib non-free 
  - sudo apt-get install mono mono-devel 
  - sudo apt-get install monodevelop 


script:
  - xbuild TestProject2.sln
  - nunit-console TestProject2/bin/Debug/TestProject2.dll
  
