## Travis CI Integration

language: c

install:
  - cd monodevelop
  - ./configure 
  - make
  - sudo make install


script:
  - xbuild TestProject2.sln
  - nunit-console TestProject2/bin/Debug/TestProject2.dll
  
