## Travis CI Integration

language: c

install:
  - sudo wget http://download.mono-project.com/archive/3.0.10/macos-10-x86/MonoFramework-MDK-3.0.10.macos10.xamarin.x86.dmg
  - sudo hdid MonoFramework-MDK-3.0.10.macos10.xamarin.x86.dmg
  - sudo installer -pkg "/Volumes/Mono Framework MDK 3.0.10/MonoFramework-MDK-3.0.10.macos10.xamarin.x86.pkg" -target /

script:
  - xbuild TestProject2.sln
  - nunit-console TestProject2/bin/Debug/TestProject2.dll
  
