## Travis CI Integration

language: c

install:
 - sudo apt-get install mono-complete
 - sudo apt-get install  monodevelop
 - sudo apt-get install monodevelop-nunit monodoc-nunit-manual
 


script:
  - xbuild TestProject2.sln
  - nunit-console TestProject2/bin/Debug/TestProject2.dll
  
